server:
  port: 9012

spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.160.129:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

jwt:
  config:
    key: yfli

eureka:                                     #添加注册eureka服务的配置
  client:
    service‐url:
      defaultZone: http://127.0.0.1:6868/eureka
    instance:
      prefer‐ip‐address: true
